import Papa from "papaparse";
import { format, parse } from "date-fns";
import { fromZonedTime } from "date-fns-tz";
import { groupExecutions, type Fill, type PositionCycle } from "./trades";

type CsvRow = Record<string, string | undefined>;
export type ImportTrade = { symbol:string; assetClass:"STOCK"|"FUTURE"|"FOREX"; multiplier:string; cycle:PositionCycle; setup?:string; newsOnDay?:string; notes?:string };
export type TradeImportResult = { format:"tradingview-orders"|"tradingview-trades"|"tradingview-strategy"|"tfxzella"; rowCount:number; trades:ImportTrade[]; errors:{row:number;message:string}[] };

const key=(value:string)=>value.replace(/^\uFEFF/,"").toLowerCase().replace(/[^a-z0-9]/g,"");
const normalize=(row:CsvRow)=>Object.fromEntries(Object.entries(row).map(([name,value])=>[key(name),value?.trim()??""]));
function required(row:CsvRow,names:string[],label:string){for(const name of names){const value=row[key(name)];if(value)return value}throw new Error(`Missing ${label}`)}
function numberValue(value:string,label:string,positive=true){const parenthesized=/^\(.*\)$/.test(value.trim());const cleaned=value.replace(/[−–—]/g,"-").replace(/[()]/g,"").replace(/[^0-9.eE+-]/g,"");const parsed=Number(cleaned)*(parenthesized?-1:1);if(!Number.isFinite(parsed)||(positive&&parsed<=0))throw new Error(`Invalid ${label}: ${value||"empty"}`);return String(parsed)}
function dateValue(value:string,timezone:string){if(!value)throw new Error("Missing date/time");const hasOffset=/(?:Z|[+-]\d{2}:?\d{2})$/i.test(value);let normalized=value.replace(/^(\d{4}-\d{2}-\d{2})\s+/,"$1T");if(/^[A-Za-z]{3}\s+\d{1,2},\s+\d{4},/.test(value)){const local=parse(value,"MMM d, yyyy, HH:mm",new Date());normalized=format(local,"yyyy-MM-dd'T'HH:mm:ss")}const parsed=hasOffset?new Date(normalized):fromZonedTime(normalized,timezone);if(Number.isNaN(parsed.getTime()))throw new Error(`Invalid date/time: ${value}`);return parsed}
function assetClass(value?:string):ImportTrade["assetClass"]{const normalized=value?.trim().toUpperCase();if(!normalized)return "STOCK";if(normalized==="STOCK"||normalized==="FUTURE"||normalized==="FOREX")return normalized;throw new Error(`Unsupported asset class: ${value}`)}
function parseCsv(source:string){const parsed=Papa.parse<CsvRow>(source,{header:true,skipEmptyLines:"greedy",transformHeader:header=>header.trim()});if(parsed.errors.length)throw new Error(parsed.errors[0].message);if(!parsed.meta.fields?.length)throw new Error("The CSV has no header row");return{rows:parsed.data.map(normalize),headers:parsed.meta.fields.map(key)}}
function cycleFromPair(row:CsvRow,timezone:string){const direction=required(row,["direction"],"direction").toUpperCase();if(direction!=="LONG"&&direction!=="SHORT")throw new Error(`Invalid direction: ${direction}`);const quantity=numberValue(required(row,["quantity"],"quantity"),"quantity"),entry=numberValue(required(row,["entry"],"entry price"),"entry price"),exit=numberValue(required(row,["exit"],"exit price"),"exit price"),fees=numberValue(row.fees||"0","fees",false);return[{side:direction==="LONG"?"BUY":"SELL",quantity,price:entry,executedAt:dateValue(required(row,["openedAt"],"open date"),timezone)},{side:direction==="LONG"?"SELL":"BUY",quantity,price:exit,fees,executedAt:dateValue(required(row,["closedAt"],"close date"),timezone)}] satisfies Fill[]}

export function parseTradeImport(source:string,options:{timezone?:string;strategySymbol?:string;assetClass?:string;multiplier?:string}={}):TradeImportResult{
 const timezone=options.timezone||"UTC";try{new Intl.DateTimeFormat("en",{timeZone:timezone}).format()}catch{throw new Error(`Invalid timezone: ${timezone}`)}
 const{rows,headers}=parseCsv(source);if(rows.length>5000)throw new Error("Imports are limited to 5,000 rows");const has=(name:string)=>headers.includes(key(name));const errors:TradeImportResult["errors"]=[],fallbackAsset=assetClass(options.assetClass),fallbackMultiplier=numberValue(options.multiplier||"1","multiplier");
 if(has("Fill Price")&&has("Closing Time")&&has("Side")&&has("Symbol")){const bySymbol=new Map<string,Fill[]>();rows.forEach((row,index)=>{if(row.status&&row.status.toUpperCase()!=="FILLED")return;try{const symbol=required(row,["symbol"],"symbol").toUpperCase(),side=required(row,["side"],"side").toUpperCase();if(side!=="BUY"&&side!=="SELL")throw new Error(`Invalid side: ${side}`);const fill:Fill={side,quantity:numberValue(required(row,["qty","quantity"],"quantity"),"quantity"),price:numberValue(required(row,["fillprice","price"],"fill price"),"fill price"),commission:numberValue(row.commission||"0","commission",false),executedAt:dateValue(required(row,["closingtime","date"],"closing time"),timezone)};bySymbol.set(symbol,[...(bySymbol.get(symbol)||[]),fill])}catch(error){errors.push({row:index+2,message:error instanceof Error?error.message:"Invalid row"})}});const trades=[...bySymbol].flatMap(([symbol,fills])=>groupExecutions(fills,fallbackMultiplier).map(cycle=>({symbol,assetClass:fallbackAsset,multiplier:fallbackMultiplier,cycle})));return{format:"tradingview-orders",rowCount:rows.length,trades,errors}}
 if(has("Trade number")&&has("Size (qty)")&&has("Symbol")&&has("Type")){const grouped=new Map<string,CsvRow[]>();rows.forEach(row=>{const id=`${row.symbol}:${row.tradenumber}`;grouped.set(id,[...(grouped.get(id)||[]),row])});const trades:ImportTrade[]=[];for(const group of grouped.values()){try{const entry=group.find(row=>row.type?.toLowerCase().includes("entry")),exit=group.find(row=>row.type?.toLowerCase().includes("exit"));if(!entry||!exit)throw new Error(`Trade ${group[0].tradenumber||""} is missing an entry or exit`);const type=entry.type!.toLowerCase(),direction=type.includes("short")?"SHORT":"LONG",quantity=numberValue(required(entry,["sizeqty"],"size"),"size"),entryPrice=numberValue(required(entry,["price"],"entry price"),"entry price"),exitPrice=numberValue(required(exit,["price"],"exit price"),"exit price"),commission=numberValue(exit.commissionusd||entry.commissionusd||"0","commission",false),reportedNet=Number((exit.netpnlusd||entry.netpnlusd||"").replace(/[^0-9.eE+-]/g,""));const rawGross=(Number(exitPrice)-Number(entryPrice))*Number(quantity)*(direction==="LONG"?1:-1),inferred=Number.isFinite(reportedNet)&&rawGross!==0?(reportedNet+Number(commission))/rawGross:Number(fallbackMultiplier),multiplier=inferred>0?String(inferred):fallbackMultiplier;const fills:Fill[]=[{side:direction==="LONG"?"BUY":"SELL",quantity,price:entryPrice,executedAt:dateValue(required(entry,["dateandtime"],"entry time"),timezone)},{side:direction==="LONG"?"SELL":"BUY",quantity,price:exitPrice,commission,executedAt:dateValue(required(exit,["dateandtime"],"exit time"),timezone)}];const[cycle]=groupExecutions(fills,multiplier);trades.push({symbol:required(entry,["symbol"],"symbol").toUpperCase(),assetClass:fallbackAsset,multiplier,cycle})}catch(error){errors.push({row:2,message:error instanceof Error?error.message:"Invalid trade"})}}return{format:"tradingview-trades",rowCount:rows.length,trades,errors}}
 if(has("Trade #")&&has("Type")&&has("Date and time")&&has("Price")){const symbol=options.strategySymbol?.trim().toUpperCase();if(!symbol)throw new Error("Enter the chart symbol for this TradingView Strategy Tester export");const fills:Fill[]=[];rows.forEach((row,index)=>{try{const type=required(row,["type"],"trade type").toLowerCase();let side:Fill["side"];if(type.includes("long"))side=type.includes("exit")?"SELL":"BUY";else if(type.includes("short"))side=type.includes("exit")?"BUY":"SELL";else throw new Error(`Unsupported trade type: ${row.type}`);fills.push({side,quantity:numberValue(required(row,["contracts","positionsize","qty","quantity"],"position size"),"position size"),price:numberValue(required(row,["price"],"price"),"price"),executedAt:dateValue(required(row,["dateandtime","datetime"],"date/time"),timezone)})}catch(error){errors.push({row:index+2,message:error instanceof Error?error.message:"Invalid row"})}});const trades=groupExecutions(fills,fallbackMultiplier).map(cycle=>({symbol,assetClass:fallbackAsset,multiplier:fallbackMultiplier,cycle}));return{format:"tradingview-strategy",rowCount:rows.length,trades,errors}}
 if(has("symbol")&&has("direction")&&has("entry")&&has("exit")){const trades:ImportTrade[]=[];rows.forEach((row,index)=>{try{const multiplier=numberValue(row.multiplier||fallbackMultiplier,"multiplier"),[cycle]=groupExecutions(cycleFromPair(row,timezone),multiplier);trades.push({symbol:required(row,["symbol"],"symbol").toUpperCase(),assetClass:assetClass(row.assetclass||options.assetClass),multiplier,cycle,setup:row.setup||undefined,newsOnDay:row.newsonday||undefined,notes:row.notes||undefined})}catch(error){errors.push({row:index+2,message:error instanceof Error?error.message:"Invalid row"})}});return{format:"tfxzella",rowCount:rows.length,trades,errors}}
 throw new Error("Unsupported CSV. Use a TradingView Transactions export, Strategy Tester trade list, or TFXZella CSV.")
}
