import Link from "next/link";
import { formatInTimeZone } from "date-fns-tz";
import { ActivityChart, BreakdownDonut, DailyPerformanceChart, PerformanceBarChart, WinLossDonut } from "@/components/performance-charts";
import { db } from "@/lib/db";
import { viewer } from "@/lib/data";
import { calculateMetrics } from "@/lib/trades";
import { duration, money, pct } from "@/lib/format";
import { minutesBetween, processScore, reviewCompleteness } from "@/lib/skill-metrics";
import { APP_TIME_ZONE, newYorkDayEnd, newYorkDayStart } from "@/lib/time";

export const metadata={title:"Reports"};
type Row={name:string;count:number;pnl:number;wins:number;durationMs:number};
type Params=Record<string,string|string[]|undefined>;
const tabs=[{id:"overview",label:"Overview"},{id:"time",label:"Day & Time"},{id:"markets",label:"Strategies & Symbols"},{id:"behavior",label:"Behavior"}] as const;

export default async function Reports({searchParams}:{searchParams:Promise<Params>}){
  const user=await viewer(),params=await searchParams,value=(key:string)=>typeof params[key]==="string"?params[key]:"",report=tabs.some(tab=>tab.id===value("report"))?value("report"):"overview",accountId=value("account"),strategyId=value("strategy"),direction=value("direction"),grade=value("grade"),from=value("from"),to=value("to"),source=value("source")==="BACKTEST"?"BACKTEST":"LIVE";
  const [accounts,playbooks]=await Promise.all([db.tradingAccount.findMany({where:{userId:user.id,archivedAt:null},orderBy:{name:"asc"}}),db.playbook.findMany({where:{userId:user.id},orderBy:{name:"asc"}})]);
  const trades=await db.trade.findMany({where:{account:{userId:user.id},source,accountId:accountId||undefined,playbookId:strategyId||undefined,direction:direction==="LONG"||direction==="SHORT"?direction:undefined,qualityGrade:grade||undefined,deletedAt:null,closedAt:{not:null,gte:from?newYorkDayStart(from):undefined,lte:to?newYorkDayEnd(to):undefined}},include:{instrument:true,account:true,playbook:true,plan:true},orderBy:{closedAt:"asc"}});
  const metrics=calculateMetrics(trades.map(trade=>({netPnl:trade.netPnl.toString(),grossPnl:trade.grossPnl.toString(),fees:trade.fees.toString(),closedAt:trade.closedAt}))),currency=trades[0]?.account.currency||accounts.find(account=>account.id===accountId)?.currency||"USD";
  const durations=trades.map(holdMs),winnerDurations=trades.filter(trade=>Number(trade.netPnl)>0).map(holdMs),loserDurations=trades.filter(trade=>Number(trade.netPnl)<0).map(holdMs);
  const scores=trades.map(processScore).filter((score):score is number=>score!==null),avgProcess=average(scores),avgCompleteness=average(trades.map(reviewCompleteness)),planUsage=trades.length?trades.filter(trade=>trade.planId).length/trades.length*100:0;
  const ruleTrades=trades.filter(trade=>Array.isArray(trade.playbook?.entryChecklist)&&trade.playbook.entryChecklist.length),ruleAdherence=ruleTrades.length?average(ruleTrades.map(trade=>trade.checkedRules.length/(trade.playbook!.entryChecklist as unknown[]).length*100)):0;
  const riskTrades=trades.filter(trade=>trade.initialRisk&&trade.plan?.riskBudget),riskCompliance=riskTrades.length?riskTrades.filter(trade=>Number(trade.initialRisk)<=Number(trade.plan!.riskBudget)).length/riskTrades.length*100:0;
  const postLoss=trades.slice(1).flatMap((trade,index)=>{const previous=trades[index];return Number(previous.netPnl)<0&&previous.closedAt?[{latency:minutesBetween(previous.closedAt,trade.openedAt),trade}]:[]}),quickReentries=postLoss.filter(item=>item.latency<=30);
  const byDuration=group(trades,trade=>durationBand(holdMs(trade))),byHour=group(trades,trade=>`${formatInTimeZone(trade.openedAt,APP_TIME_ZONE,"HH:00")}`),byWeekday=group(trades,trade=>formatInTimeZone(trade.openedAt,APP_TIME_ZONE,"EEEE")),bySymbol=group(trades,trade=>trade.instrument.symbol),byStrategy=group(trades,trade=>trade.playbook?.name||trade.setup||"Unassigned"),byGrade=group(trades,trade=>trade.qualityGrade?`${trade.qualityGrade}-grade`:"Not graded"),byDiscipline=group(trades,trade=>trade.followedPlan===true?"On-plan":trade.followedPlan===false?"Off-plan":"Not reviewed"),byEmotion=group(trades,trade=>trade.emotion||"Not recorded"),byConfidence=group(trades,trade=>trade.confidence?`${trade.confidence}/5 confidence`:"Not recorded"),byCondition=group(trades,trade=>trade.marketCondition||"Not recorded"),byMistake=group(trades.flatMap(trade=>trade.mistakes.length?trade.mistakes.map(mistake=>({...trade,mistake})):[{...trade,mistake:"No mistake recorded"}]),trade=>trade.mistake);
  const dailyMap=new Map<string,{name:string;value:number;count:number;cumulative:number}>();let cumulative=0;for(const trade of trades){const name=formatInTimeZone(trade.closedAt!,APP_TIME_ZONE,"MMM d"),point=dailyMap.get(name)||{name,value:0,count:0,cumulative:0};point.value+=Number(trade.netPnl);point.count++;dailyMap.set(name,point)}const daily=[...dailyMap.values()].map(point=>({...point,cumulative:cumulative+=point.value}));
  const filterQuery=new URLSearchParams(Object.entries({source,account:accountId,strategy:strategyId,direction,grade,from,to}).filter(([,entry])=>entry));
  return <div className="content reports-page">
    <div className="page-head"><div><span className="eyebrow">Reports</span><h1>Performance analysis</h1><p>Start with the summary, then drill into one question at a time.</p></div><a className="btn secondary" href="/api/export?format=csv">Export data</a></div>
    <nav className="report-tabs">{tabs.map(tab=><Link className={report===tab.id?"active":""} key={tab.id} href={`/app/analytics?report=${tab.id}${filterQuery.size?`&${filterQuery}`:""}`}>{tab.label}</Link>)}</nav>
    <form className="report-filter-bar"><input type="hidden" name="report" value={report}/><Filter label="Trading mode"><select name="source" defaultValue={source}><option value="LIVE">Live</option><option value="BACKTEST">Backtest</option></select></Filter><Filter label="Account"><select name="account" defaultValue={accountId}><option value="">All accounts</option>{accounts.map(account=><option key={account.id} value={account.id}>{account.name}</option>)}</select></Filter><Filter label="Date from"><input name="from" type="date" defaultValue={from}/></Filter><Filter label="Date to"><input name="to" type="date" defaultValue={to}/></Filter><Filter label="Strategy"><select name="strategy" defaultValue={strategyId}><option value="">All strategies</option>{playbooks.map(playbook=><option key={playbook.id} value={playbook.id}>{playbook.name}</option>)}</select></Filter><Filter label="Direction"><select name="direction" defaultValue={direction}><option value="">All sides</option><option>LONG</option><option>SHORT</option></select></Filter><Filter label="Grade"><select name="grade" defaultValue={grade}><option value="">All grades</option><option>A</option><option>B</option><option>C</option></select></Filter><button className="btn">Apply</button><Link className="btn secondary" href={`/app/analytics?report=${report}`}>Clear</Link></form>
    <section className="report-kpis"><Metric name="Net P&L" value={money(metrics.netPnl.toString(),currency)} tone={metrics.netPnl.gte(0)?"positive":"negative"}/><Metric name="Profit factor" value={metrics.profitFactor?.toFixed(2)||(metrics.wins?"∞":"0.00")}/><Metric name="Win rate" value={pct(metrics.winRate.toString())}/><Metric name="Expectancy" value={money(metrics.expectancy.toString(),currency)}/><Metric name="Process score" value={scores.length?pct(avgProcess):"—"}/><Metric name="Journal complete" value={trades.length?pct(avgCompleteness):"—"}/></section>
    {report==="overview"?<Overview metrics={metrics} daily={daily} currency={currency} byStrategy={byStrategy} bySymbol={bySymbol}/>:null}
    {report==="time"?<TimeReport byHour={byHour} byWeekday={byWeekday} byDuration={byDuration} durations={durations} winnerDurations={winnerDurations} loserDurations={loserDurations} currency={currency}/>:null}
    {report==="markets"?<MarketsReport byStrategy={byStrategy} bySymbol={bySymbol} currency={currency}/>:null}
    {report==="behavior"?<BehaviorReport byDiscipline={byDiscipline} byGrade={byGrade} byEmotion={byEmotion} byConfidence={byConfidence} byCondition={byCondition} byMistake={byMistake} currency={currency} planUsage={planUsage} ruleAdherence={ruleAdherence} riskCompliance={riskCompliance} postLossCount={postLoss.length} quickReentries={quickReentries.length} averageReentry={average(postLoss.map(item=>item.latency))}/>:null}
  </div>;
}

function Overview({metrics,daily,currency,byStrategy,bySymbol}:{metrics:ReturnType<typeof calculateMetrics>;daily:{name:string;value:number;count:number;cumulative:number}[];currency:string;byStrategy:Row[];bySymbol:Row[]}){const best=byStrategy[0],worst=[...byStrategy].sort((a,b)=>a.pnl-b.pnl)[0],active=[...bySymbol].sort((a,b)=>b.count-a.count)[0],highest=[...byStrategy].filter(row=>row.count).sort((a,b)=>b.wins/b.count-a.wins/a.count)[0];return <><section className="performance-summary section"><Insight label="Best performing" value={best?.name||"—"} detail={best?money(best.pnl,currency):"No data"} tone="positive"/><Insight label="Least performing" value={worst?.name||"—"} detail={worst?money(worst.pnl,currency):"No data"} tone="negative"/><Insight label="Most active symbol" value={active?.name||"—"} detail={active?`${active.count} trades`:"No data"}/><Insight label="Highest win rate" value={highest?.name||"—"} detail={highest?pct(highest.wins/highest.count*100):"No data"}/></section><div className="report-primary section"><section className="card chart-card"><ReportTitle kicker="Account curve" title="Daily & cumulative net P&L"/><DailyPerformanceChart data={daily}/></section><section className="card chart-card"><ReportTitle kicker={`${metrics.totalTrades} closed trades`} title="Outcome distribution"/><WinLossDonut wins={metrics.wins} losses={metrics.losses} breakeven={metrics.totalTrades-metrics.wins-metrics.losses}/></section></div></>}

function TimeReport({byHour,byWeekday,byDuration,durations,winnerDurations,loserDurations,currency}:{byHour:Row[];byWeekday:Row[];byDuration:Row[];durations:number[];winnerDurations:number[];loserDurations:number[];currency:string}){return <><section className="duration-strip section"><Insight label="Average hold" value={duration(average(durations))} detail="All trades"/><Insight label="Winning hold" value={duration(average(winnerDurations))} detail="Average winner" tone="positive"/><Insight label="Losing hold" value={duration(average(loserDurations))} detail="Average loser" tone="negative"/><Insight label="Hold-time gap" value={duration(Math.abs(average(winnerDurations)-average(loserDurations)))} detail="Winner vs loser"/></section><div className="report-primary section"><section className="card chart-card"><ReportTitle kicker="Trade frequency" title="Entries by hour"/><ActivityChart data={chart(byHour)}/></section><section className="card"><ReportTitle kicker="Performance" title="Day of week"/><CompactRows rows={byWeekday} currency={currency}/></section></div><section className="card section"><ReportTitle kicker="Holding behavior" title="Performance by duration"/><Distribution rows={byDuration} currency={currency}/></section></>}

function MarketsReport({byStrategy,bySymbol,currency}:{byStrategy:Row[];bySymbol:Row[];currency:string}){return <><section className="performance-summary section"><SummaryFromRows rows={byStrategy} currency={currency}/></section><div className="report-primary section"><section className="card chart-card"><ReportTitle kicker="Net P&L comparison" title="Strategy performance"/><PerformanceBarChart data={chart(byStrategy.slice(0,8))}/></section><section className="card"><ReportTitle kicker="Ranked by result" title="Strategies"/><CompactRows rows={byStrategy} currency={currency}/></section></div><section className="card section"><ReportTitle kicker="Market focus" title="Symbols"/><CompactRows rows={bySymbol} currency={currency}/></section></>}

function BehaviorReport({byDiscipline,byGrade,byEmotion,byConfidence,byCondition,byMistake,currency,planUsage,ruleAdherence,riskCompliance,postLossCount,quickReentries,averageReentry}:{byDiscipline:Row[];byGrade:Row[];byEmotion:Row[];byConfidence:Row[];byCondition:Row[];byMistake:Row[];currency:string;planUsage:number;ruleAdherence:number;riskCompliance:number;postLossCount:number;quickReentries:number;averageReentry:number}){return <><section className="performance-summary section"><Insight label="Plan usage" value={pct(planUsage)} detail="Trades linked to a daily plan"/><Insight label="Rule adherence" value={pct(ruleAdherence)} detail="Playbook checks completed"/><Insight label="Risk compliance" value={pct(riskCompliance)} detail="Trades within planned budget"/><Insight label="Post-loss reset" value={postLossCount?`${averageReentry.toFixed(0)} min`:"—"} detail={postLossCount?`${quickReentries} of ${postLossCount} re-entered within 30m`:"No post-loss sample"}/></section><div className="report-primary section"><section className="card chart-card"><ReportTitle kicker="Process" title="Plan adherence"/><BreakdownDonut data={byDiscipline.map(row=>({name:row.name,value:row.count}))}/></section><section className="card chart-card"><ReportTitle kicker="Self-assessment" title="Quality grades"/><BreakdownDonut data={byGrade.map(row=>({name:row.name,value:row.count}))}/></section></div><div className="behavior-grid section"><section className="card"><ReportTitle kicker="Outcome calibration" title="Pre-trade confidence"/><CompactRows rows={byConfidence} currency={currency}/></section><section className="card"><ReportTitle kicker="P&L when the behavior appears" title="Mistake patterns"/><CompactRows rows={byMistake} currency={currency}/></section><section className="card"><ReportTitle kicker="Mental performance" title="Emotional state"/><CompactRows rows={byEmotion} currency={currency}/></section><section className="card"><ReportTitle kicker="Context" title="Market condition"/><CompactRows rows={byCondition} currency={currency}/></section></div></>}

function holdMs(trade:{openedAt:Date;closedAt:Date|null}){return trade.closedAt?Math.max(0,trade.closedAt.getTime()-trade.openedAt.getTime()):0}function average(values:number[]){return values.length?values.reduce((sum,current)=>sum+current,0)/values.length:0}function durationBand(ms:number){const minutes=ms/60_000;return minutes<5?"Under 5m":minutes<15?"5–15m":minutes<30?"15–30m":minutes<60?"30–60m":minutes<240?"1–4h":"4h+"}function group<T extends {netPnl:unknown;openedAt:Date;closedAt:Date|null}>(trades:T[],key:(trade:T)=>string){return Object.values(trades.reduce<Record<string,Row>>((all,trade)=>{const name=key(trade);all[name]??={name,count:0,pnl:0,wins:0,durationMs:0};all[name].count++;all[name].pnl+=Number(trade.netPnl);all[name].durationMs+=holdMs(trade);if(Number(trade.netPnl)>0)all[name].wins++;return all},{})).sort((a,b)=>b.pnl-a.pnl)}function chart(rows:Row[]){return rows.map(row=>({name:row.name,value:row.pnl,count:row.count}))}
function Filter({label,children}:{label:string;children:React.ReactNode}){return <label className="field"><span>{label}</span>{children}</label>}function Metric({name,value,tone}:{name:string;value:string;tone?:string}){return <div className="report-metric"><span>{name}</span><strong className={tone}>{value}</strong></div>}function Insight({label,value,detail,tone}:{label:string;value:string;detail:string;tone?:string}){return <article className="insight-card"><span>{label}</span><strong>{value}</strong><small className={tone}>{detail}</small></article>}function ReportTitle({kicker,title}:{kicker:string;title:string}){return <div className="widget-head"><div><span className="stat-label">{kicker}</span><h2>{title}</h2></div></div>}
function CompactRows({rows,currency}:{rows:Row[];currency:string}){return <div className="compact-report">{rows.slice(0,8).map((row,index)=><div key={row.name}><span className="rank">{index+1}</span><div><b>{row.name}</b><small>{row.count} trades · {pct(row.count?row.wins/row.count*100:0)} wins</small></div><strong className={row.pnl>=0?"positive":"negative"}>{money(row.pnl,currency)}</strong></div>)}</div>}
function Distribution({rows,currency}:{rows:Row[];currency:string}){const max=Math.max(1,...rows.map(row=>row.count));return <div className="distribution-list">{rows.map(row=><div key={row.name}><span>{row.name}</span><div><i style={{width:`${row.count/max*100}%`}}/></div><b>{row.count}</b><strong className={row.pnl>=0?"positive":"negative"}>{money(row.pnl,currency)}</strong></div>)}</div>}
function SummaryFromRows({rows,currency}:{rows:Row[];currency:string}){const best=rows[0],worst=[...rows].sort((a,b)=>a.pnl-b.pnl)[0],active=[...rows].sort((a,b)=>b.count-a.count)[0],highest=[...rows].filter(row=>row.count).sort((a,b)=>b.wins/b.count-a.wins/a.count)[0];return <><Insight label="Best performing" value={best?.name||"—"} detail={best?money(best.pnl,currency):"No data"} tone="positive"/><Insight label="Least performing" value={worst?.name||"—"} detail={worst?money(worst.pnl,currency):"No data"} tone="negative"/><Insight label="Most active" value={active?.name||"—"} detail={active?`${active.count} trades`:"No data"}/><Insight label="Highest win rate" value={highest?.name||"—"} detail={highest?pct(highest.wins/highest.count*100):"No data"}/></>}
