import { addDays, endOfMonth, endOfWeek, format, startOfMonth, startOfWeek } from "date-fns";
import { formatInTimeZone } from "date-fns-tz";
import { CalendarImageExport } from "@/components/calendar-image-export";
import { db } from "@/lib/db";
import { viewer } from "@/lib/data";
import { money, pct } from "@/lib/format";
import { APP_TIME_ZONE } from "@/lib/time";
export const metadata={title:"Calendar"};
type Day={date:Date;pnl:number;count:number;wins:number;currency:string};

export default async function CalendarPage({searchParams}:{searchParams:Promise<{month?:string;account?:string}>}){
  const user=await viewer(),query=await searchParams,accountList=await db.tradingAccount.findMany({where:{userId:user.id,archivedAt:null},orderBy:{createdAt:"asc"}}),accountId=accountList.some(account=>account.id===query.account)?query.account:accountList[0]?.id,account=accountList.find(item=>item.id===accountId),requested=query.month?new Date(`${query.month}-01T12:00:00Z`):new Date(),start=startOfWeek(startOfMonth(requested),{weekStartsOn:1}),end=endOfWeek(endOfMonth(requested),{weekStartsOn:1});
  const trades=await db.trade.findMany({where:{account:{userId:user.id},accountId,source:"LIVE",deletedAt:null,closedAt:{gte:addDays(start,-1),lte:addDays(end,1)}},include:{account:true}}),days:Day[]=[];
  for(let date=start;date<=end;date=addDays(date,1)){const key=format(date,"yyyy-MM-dd"),items=trades.filter(trade=>formatInTimeZone(trade.closedAt!,APP_TIME_ZONE,"yyyy-MM-dd")===key);days.push({date:new Date(date),pnl:items.reduce((sum,trade)=>sum+Number(trade.netPnl),0),count:items.length,wins:items.filter(trade=>Number(trade.netPnl)>0).length,currency:account?.currency||"USD"})}
  const weeks=Array.from({length:days.length/7},(_,index)=>days.slice(index*7,index*7+7)),monthDays=days.filter(day=>day.date.getMonth()===requested.getMonth()),monthPnl=monthDays.reduce((sum,day)=>sum+day.pnl,0),tradingDays=monthDays.filter(day=>day.count),winningDays=tradingDays.filter(day=>day.pnl>0).length;
  const monthKey=format(requested,"yyyy-MM");
  return <div className="content"><div className="page-head"><div><span className="eyebrow">Calendar report</span><h1>{format(requested,"MMMM yyyy")}</h1><p>Daily results with automatic weekly and monthly rollups.</p></div><div className="actions"><form><input type="hidden" name="month" value={monthKey}/><select name="account" defaultValue={accountId} onChange={undefined}>{accountList.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select><button className="btn secondary">View</button></form><CalendarImageExport month={monthKey}/><a className="btn secondary" href={`?month=${format(addDays(startOfMonth(requested),-1),"yyyy-MM")}&account=${accountId}`}>←</a><a className="btn secondary" href={`?month=${format(addDays(endOfMonth(requested),1),"yyyy-MM")}&account=${accountId}`}>→</a></div></div>
    <div id="social-calendar" className="social-calendar"><header className="social-calendar-head"><div><span className="brand-mark">T</span><b>TFX<span>Zella</span></b></div><div><strong>{format(requested,"MMMM yyyy")}</strong><small>{account?.name||"Trading account"} · Performance calendar</small></div></header><section className="calendar-summary"><Summary label="Monthly net" value={money(monthPnl,account?.currency||"USD")} tone={monthPnl>=0?"positive":"negative"}/><Summary label="Trading days" value={String(tradingDays.length)}/><Summary label="Winning days" value={String(winningDays)}/><Summary label="Day win rate" value={pct(tradingDays.length?winningDays/tradingDays.length*100:0)}/></section>
    <div className="calendar-wrap section"><div className="calendar">{["Mon","Tue","Wed","Thu","Fri","Sat","Sun","Week"].map(label=><b className="stat-label" key={label}>{label}</b>)}{weeks.flatMap((week,weekIndex)=>{const weekPnl=week.reduce((sum,day)=>sum+day.pnl,0);return [...week.map(day=><div className={`day ${day.date.getMonth()!==requested.getMonth()?"muted":""} ${day.pnl>0?"profit-day":day.pnl<0?"loss-day":""}`} key={day.date.toISOString()}><div className="num">{format(day.date,"d")}</div>{day.count>0?<><div className={`pnl ${day.pnl>=0?"positive":"negative"}`}>{money(day.pnl,day.currency)}</div><small>{day.count} trade{day.count===1?"":"s"} · {pct(day.wins/day.count*100)}</small></>:null}</div>),<div className="day week-total" key={`week-${weekIndex}`}><div className="num">WEEK {weekIndex+1}</div><div className={`pnl ${weekPnl>=0?"positive":"negative"}`}>{money(weekPnl,account?.currency||"USD")}</div><small>{week.reduce((sum,day)=>sum+day.count,0)} trades</small></div>]})}</div></div><footer className="social-calendar-foot">Built with discipline · TFXZella</footer></div>
  </div>;
}
function Summary({label,value,tone}:{label:string;value:string;tone?:string}){return <div className="card"><span className="stat-label">{label}</span><div className={`stat-value ${tone||""}`}>{value}</div></div>}
