import Link from "next/link";
import { createPlaybook, deletePlaybook, togglePlaybook } from "@/app/actions";
import { db } from "@/lib/db";
import { viewer } from "@/lib/data";
import { money, pct } from "@/lib/format";
import { SubmitButton } from "@/components/confirm-submit-button";

export const metadata={title:"Playbooks"};
export default async function Playbooks(){
  const user=await viewer(),rows=await db.playbook.findMany({where:{userId:user.id},include:{trades:{where:{deletedAt:null,closedAt:{not:null}}}},orderBy:{createdAt:"desc"}});
  return <div className="content"><div className="page-head"><div><span className="eyebrow">Codify and prove your edge</span><h1>Playbooks</h1><p>Define the rules, attach trades, and verify which setups actually work.</p></div></div><div className="grid playbook-layout">
    <form action={createPlaybook} className="card form-grid playbook-form"><h2 className="full">New playbook</h2><Field name="name" label="Strategy name"/><Field name="description" label="When do you use it?" area full/><Field name="setupCriteria" label="Setup criteria" area full/><Field name="invalidationRules" label="Invalidation rules" area full/><Field name="riskRules" label="Risk rules" area full/><Field name="entryChecklist" label="Entry checklist · one rule per line" area full/><Field name="exitChecklist" label="Exit checklist · one rule per line" area full/><Field name="examples" label="Example notes or chart references" area full/><SubmitButton className="btn" pendingLabel="Creating playbook…" successMessage="Playbook created">Create playbook</SubmitButton></form>
    <section className="grid">{rows.length?rows.map(playbook=>{const trades=playbook.trades,wins=trades.filter(trade=>Number(trade.netPnl)>0),losses=trades.filter(trade=>Number(trade.netPnl)<0),net=trades.reduce((sum,trade)=>sum+Number(trade.netPnl),0),grossWins=wins.reduce((sum,trade)=>sum+Number(trade.netPnl),0),grossLoss=Math.abs(losses.reduce((sum,trade)=>sum+Number(trade.netPnl),0)),reviewed=trades.filter(trade=>trade.followedPlan!==null),adherence=reviewed.length?reviewed.filter(trade=>trade.followedPlan).length/reviewed.length*100:0;return <article className="card" key={playbook.id}><div className="review-card-head"><div><h2>{playbook.name}</h2><p>{playbook.description||"No description yet."}</p></div><span className="badge">{playbook.isActive?"ACTIVE":"ARCHIVED"}</span></div><div className="review-mini-stats"><div><span>Trades</span><b>{trades.length}</b></div><div><span>Win rate</span><b>{pct(trades.length?wins.length/trades.length*100:0)}</b></div><div><span>Profit factor</span><b>{grossLoss?(grossWins/grossLoss).toFixed(2):grossWins?"∞":"0.00"}</b></div><div><span>Rule adherence</span><b>{reviewed.length?pct(adherence):"—"}</b></div></div><div className={net>=0?"positive":"negative"}><b>{money(net,"USD")} strategy P&amp;L</b></div><div className="actions section"><Link className="btn" href={`/app/playbooks/${playbook.id}`}>View performance</Link><Link className="btn secondary" href={`/app/playbooks/${playbook.id}/edit`}>Edit rules</Link><form action={togglePlaybook}><input type="hidden" name="id" value={playbook.id}/><input type="hidden" name="active" value={String(playbook.isActive)}/><button className="btn secondary">{playbook.isActive?"Archive":"Activate"}</button></form><form action={deletePlaybook}><input type="hidden" name="id" value={playbook.id}/><button className="btn danger">Delete</button></form></div></article>}) : <div className="card empty">Build a playbook for your best setup.</div>}</section>
  </div></div>;
}
function Field({name,label,area,full}:{name:string;label:string;area?:boolean;full?:boolean}){return <div className={`field ${full?"full":""}`}><label>{label}</label>{area?<textarea name={name}/>:<input name={name} required/>}</div>}
