import Link from "next/link";
import { ArrowRight, Plus } from "lucide-react";
import { format } from "date-fns";
import { formatInTimeZone } from "date-fns-tz";
import { DailyPerformanceChart, PerformanceBarChart, WinLossDonut } from "@/components/performance-charts";
import { db } from "@/lib/db";
import { viewer } from "@/lib/data";
import { calculateMetrics } from "@/lib/trades";
import { duration, money, pct } from "@/lib/format";
import { APP_TIME_ZONE, isSameTradingDay } from "@/lib/time";

export default async function Dashboard(){
  const user=await viewer(),trades=await db.trade.findMany({where:{account:{userId:user.id},source:"LIVE",deletedAt:null,closedAt:{not:null}},include:{instrument:true,account:true,playbook:true},orderBy:{closedAt:"asc"}}),metrics=calculateMetrics(trades.map(trade=>({netPnl:trade.netPnl.toString(),grossPnl:trade.grossPnl.toString(),fees:trade.fees.toString(),closedAt:trade.closedAt}))),currency=trades[0]?.account.currency||"USD";
  const dailyMap=new Map<string,{name:string;value:number;count:number;cumulative:number}>(),strategyMap=new Map<string,{name:string;value:number;count:number}>();let cumulative=0;
  for(const trade of trades){const key=formatInTimeZone(trade.closedAt!,APP_TIME_ZONE,"MMM d"),existing=dailyMap.get(key)||{name:key,value:0,count:0,cumulative:0};existing.value+=Number(trade.netPnl);existing.count++;dailyMap.set(key,existing);const strategy=trade.playbook?.name||trade.setup||"Unassigned",strategyRow=strategyMap.get(strategy)||{name:strategy,value:0,count:0};strategyRow.value+=Number(trade.netPnl);strategyRow.count++;strategyMap.set(strategy,strategyRow)}
  const daily=[...dailyMap.values()].slice(-20).map(point=>({...point,cumulative:cumulative+=point.value})),strategies=[...strategyMap.values()].sort((a,b)=>Math.abs(b.value)-Math.abs(a.value)).slice(0,6),recent=trades.slice(-5).reverse(),reviewed=trades.filter(trade=>trade.followedPlan!==null),discipline=reviewed.length?reviewed.filter(trade=>trade.followedPlan).length/reviewed.length*100:0,holdTimes=trades.map(trade=>trade.closedAt!.getTime()-trade.openedAt.getTime()),averageHold=holdTimes.length?holdTimes.reduce((sum,value)=>sum+value,0)/holdTimes.length:0;
  const now=new Date(),todayTrades=trades.filter(trade=>isSameTradingDay(trade.closedAt!,now,APP_TIME_ZONE)),todayWins=todayTrades.filter(trade=>Number(trade.netPnl)>0).length,todayWinRate=todayTrades.length?pct(todayWins/todayTrades.length*100):"—";
  const monthKey=formatInTimeZone(now,APP_TIME_ZONE,"yyyy-MM"),month=new Date(`${monthKey}-01T12:00:00Z`),monthTrades=trades.filter(trade=>formatInTimeZone(trade.closedAt!,APP_TIME_ZONE,"yyyy-MM")===monthKey),monthDays=new Map<string,number>();for(const trade of monthTrades){const key=formatInTimeZone(trade.closedAt!,APP_TIME_ZONE,"yyyy-MM-dd");monthDays.set(key,(monthDays.get(key)||0)+Number(trade.netPnl))}
  return <div className="content dashboard-page"><div className="page-head"><div><span className="eyebrow">Dashboard</span><h1>Performance overview</h1><p>Your results, risk, discipline and repeatable edge in one view.</p></div><Link className="btn" href="/app/journal/new"><Plus size={17}/>Add trade</Link></div>
    <section className="dashboard-kpis"><Stat label="Today's win rate" value={todayWinRate}/><Stat label="Net P&L" value={money(metrics.netPnl.toString(),currency)} tone={metrics.netPnl.gte(0)?"positive":"negative"}/><Stat label="Profit factor" value={metrics.profitFactor?.toFixed(2)||"∞"}/><Stat label="Expectancy" value={money(metrics.expectancy.toString(),currency)}/><Stat label="Avg hold" value={duration(averageHold)}/><Stat label="Discipline" value={reviewed.length?pct(discipline):"—"}/></section>
    <section className="dashboard-main section"><article className="card chart-card wide"><CardTitle eyebrow="Performance" title="Daily & cumulative net P&L" link="/app/analytics"/><DailyPerformanceChart data={daily}/></article><article className="card chart-card"><CardTitle eyebrow="Outcomes" title="Win / loss distribution"/><WinLossDonut wins={metrics.wins} losses={metrics.losses} breakeven={metrics.totalTrades-metrics.wins-metrics.losses}/></article>
      <article className="card chart-card"><CardTitle eyebrow="Edge" title="Strategy performance" link="/app/playbooks"/><PerformanceBarChart data={strategies}/></article>
      <article className="card mini-calendar-card"><CardTitle eyebrow={formatInTimeZone(now,APP_TIME_ZONE,"MMMM")} title="Trading calendar" link="/app/calendar"/><div className="mini-calendar"><div className="mini-weekdays">{"MTWTFSS".split("").map((day,index)=><span key={`${day}${index}`}>{day}</span>)}</div><div className="mini-days">{Array.from({length:42},(_,index)=>{const offset=(month.getDay()+6)%7,day=index-offset+1,date=new Date(month.getFullYear(),month.getMonth(),day),key=format(date,"yyyy-MM-dd"),pnl=monthDays.get(key);return <span className={day<1||date.getMonth()!==month.getMonth()?"muted":pnl===undefined?"":pnl>0?"win":pnl<0?"loss":"flat"} key={`${key}-${index}`}>{date.getDate()}</span>})}</div><div className="calendar-legend"><span><i className="win"/>Winning day</span><span><i className="loss"/>Losing day</span></div></div></article>
      <article className="card recent-card wide"><CardTitle eyebrow="Latest activity" title="Recent trades" link="/app/journal"/><div className="recent-trade-list">{recent.length?recent.map(trade=><Link href={`/app/journal/${trade.id}`} key={trade.id}><span className={`trade-dot ${Number(trade.netPnl)>=0?"win":"loss"}`}/><div><b>{trade.instrument.symbol}</b><small>{trade.direction} · {formatInTimeZone(trade.closedAt!,APP_TIME_ZONE,"M/d/yyyy")}</small></div><span>{duration(trade.closedAt!.getTime()-trade.openedAt.getTime())}</span><strong className={Number(trade.netPnl)>=0?"positive":"negative"}>{money(trade.netPnl.toString(),trade.account.currency)}</strong><ArrowRight size={15}/></Link>):<div className="empty">No closed trades yet.</div>}</div></article>
    </section>
  </div>;
}
function Stat({label,value,tone}:{label:string;value:string;tone?:string}){return <div className="card kpi-card"><div className="stat-label">{label}</div><div className={`stat-value ${tone||""}`}>{value}</div></div>}
function CardTitle({eyebrow,title,link}:{eyebrow:string;title:string;link?:string}){return <div className="widget-head"><div><span className="stat-label">{eyebrow}</span><h2>{title}</h2></div>{link?<Link className="widget-link" href={link}>View report <ArrowRight size={14}/></Link>:null}</div>}
