"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import type { LucideIcon } from "lucide-react";
import { BarChart3, BookOpen, CalendarDays, ChartNoAxesCombined, ChevronDown, ClipboardCheck, FlaskConical, LayoutDashboard, LogOut, NotebookPen, Plus, Settings, Upload } from "lucide-react";
import { logout } from "@/app/actions";
import { SubmitButton } from "@/components/confirm-submit-button";
import { NavigationLink } from "@/components/navigation-link";
type NavItem={label:string;icon:LucideIcon;href:string};type NavGroup={label:string;items:NavItem[]};
const groups:NavGroup[]=[{label:"Journal",items:[{label:"Dashboard",icon:LayoutDashboard,href:"/app"},{label:"Trades",icon:BookOpen,href:"/app/journal"},{label:"Backtesting",icon:FlaskConical,href:"/app/backtests"},{label:"Calendar",icon:CalendarDays,href:"/app/calendar"},{label:"Reports",icon:BarChart3,href:"/app/analytics"}]},{label:"Improve",items:[{label:"Daily plans",icon:NotebookPen,href:"/app/plans"},{label:"Strategies",icon:ClipboardCheck,href:"/app/playbooks"},{label:"Reviews",icon:ChartNoAxesCombined,href:"/app/reviews"}]},{label:"Manage",items:[{label:"Import trades",icon:Upload,href:"/app/import"},{label:"Settings",icon:Settings,href:"/app/settings"}]}];
const allItems=groups.flatMap(group=>group.items);
export function AppShell({children,name}:{children:React.ReactNode;name?:string|null}){const pathname=usePathname(),active=(href:string)=>href==="/app"?pathname===href:pathname.startsWith(href),current=allItems.find(item=>active(item.href));return <div className="shell trade-workspace"><aside className="sidebar"><Link href="/app" className="brand"><span className="brand-mark">T</span><span>TFX<span>Zella</span></span></Link><div className="account-switcher"><span className="account-avatar">{name?.[0]?.toUpperCase()||"T"}</span><div><b>{name||"Trader"}</b><small>Trading workspace</small></div><ChevronDown size={14}/></div><nav className="nav grouped-nav">{groups.map(group=><section key={group.label}><span className="nav-label">{group.label}</span>{group.items.map(item=>{const Icon=item.icon;return <NavigationLink aria-current={active(item.href)?"page":undefined} className={active(item.href)?"active":""} key={item.href} href={item.href}><Icon size={17}/><span>{item.label}</span></NavigationLink>})}</section>)}</nav><form action={logout} className="sidebar-foot"><SubmitButton className="sidebar-logout" pendingLabel="Logging out…"><LogOut size={16}/>Log out</SubmitButton></form></aside><main className="main"><header className="topbar"><div><span className="topbar-title">{current?.label||"Dashboard"}</span><span className="topbar-subtitle">Live journal</span></div><div className="topbar-actions"><NavigationLink className="btn secondary" href="/app/import"><Upload size={15}/>Import</NavigationLink><NavigationLink className="btn" href="/app/journal/new"><Plus size={16}/>Add trade</NavigationLink></div></header>{children}</main><nav className="mobile-nav" aria-label="Mobile navigation">{allItems.map(item=>{const Icon=item.icon;return <NavigationLink aria-current={active(item.href)?"page":undefined} className={active(item.href)?"active":""} key={item.href} href={item.href}><Icon size={19}/><span>{item.label}</span></NavigationLink>})}</nav></div>}
