"use client";
import { Area, Bar, BarChart, CartesianGrid, Cell, ComposedChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

type Point={name:string;value:number;count?:number;cumulative?:number};
const tooltip={background:"var(--panel)",border:"1px solid var(--line)",borderRadius:10,color:"var(--text)"};

export function DailyPerformanceChart({data}:{data:Point[]}){if(!data.length)return <Empty/>;return <ChartFrame><ComposedChart data={data} margin={{top:8,right:8,left:-12,bottom:0}}><defs><linearGradient id="cum" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#725cff" stopOpacity={.35}/><stop offset="1" stopColor="#725cff" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="var(--line)" vertical={false} strokeDasharray="3 3"/><XAxis dataKey="name" axisLine={false} tickLine={false} fontSize={11}/><YAxis axisLine={false} tickLine={false} fontSize={11}/><Tooltip contentStyle={tooltip}/><Bar dataKey="value" name="Daily P&L" radius={[4,4,0,0]}>{data.map((point,index)=><Cell key={index} fill={point.value>=0?"#2bd9a4":"#ff627d"}/>)}</Bar><Area type="monotone" dataKey="cumulative" name="Cumulative" stroke="#8c78ff" strokeWidth={2.5} fill="url(#cum)"/></ComposedChart></ChartFrame>}

export function PerformanceBarChart({data}:{data:Point[]}){if(!data.length)return <Empty/>;return <ChartFrame><BarChart data={data} layout="vertical" margin={{top:5,right:15,left:5,bottom:0}}><CartesianGrid stroke="var(--line)" horizontal={false} strokeDasharray="3 3"/><XAxis type="number" axisLine={false} tickLine={false} fontSize={11}/><YAxis type="category" dataKey="name" width={88} axisLine={false} tickLine={false} fontSize={11}/><Tooltip contentStyle={tooltip}/><Bar dataKey="value" name="Net P&L" radius={[0,5,5,0]}>{data.map((point,index)=><Cell key={index} fill={point.value>=0?"#2bd9a4":"#ff627d"}/>)}</Bar></BarChart></ChartFrame>}

export function ActivityChart({data}:{data:Point[]}){if(!data.length)return <Empty/>;return <ChartFrame><BarChart data={data} margin={{top:5,right:8,left:-20,bottom:0}}><CartesianGrid stroke="var(--line)" vertical={false} strokeDasharray="3 3"/><XAxis dataKey="name" axisLine={false} tickLine={false} fontSize={11}/><YAxis axisLine={false} tickLine={false} fontSize={11}/><Tooltip contentStyle={tooltip}/><Bar dataKey="count" name="Trades" fill="#7065f0" radius={[5,5,0,0]}/></BarChart></ChartFrame>}

export function WinLossDonut({wins,losses,breakeven}:{wins:number;losses:number;breakeven:number}){const data=[{name:"Wins",value:wins,color:"#2bd9a4"},{name:"Losses",value:losses,color:"#ff627d"},{name:"Breakeven",value:breakeven,color:"#777789"}].filter(item=>item.value);if(!data.length)return <Empty/>;return <div className="donut-wrap"><ResponsiveContainer width="100%" height={210}><PieChart><Pie data={data} dataKey="value" innerRadius={58} outerRadius={86} paddingAngle={3}>{data.map(item=><Cell key={item.name} fill={item.color}/>)}</Pie><Tooltip contentStyle={tooltip}/></PieChart></ResponsiveContainer><div className="donut-legend">{data.map(item=><span key={item.name}><i style={{background:item.color}}/>{item.name} <b>{item.value}</b></span>)}</div></div>}

export function BreakdownDonut({data}:{data:{name:string;value:number}[]}){const colors=["#725cff","#2bd9a4","#45c8ff","#f2b84b","#ff627d","#9b8aff"],clean=data.filter(item=>item.value>0);if(!clean.length)return <Empty/>;return <div className="donut-wrap"><ResponsiveContainer width="100%" height={210}><PieChart><Pie data={clean} dataKey="value" innerRadius={58} outerRadius={86} paddingAngle={3}>{clean.map((item,index)=><Cell key={item.name} fill={colors[index%colors.length]}/>)}</Pie><Tooltip contentStyle={tooltip}/></PieChart></ResponsiveContainer><div className="donut-legend">{clean.slice(0,6).map((item,index)=><span key={item.name}><i style={{background:colors[index%colors.length]}}/>{item.name} <b>{item.value}</b></span>)}</div></div>}

function ChartFrame({children}:{children:React.ReactNode}){return <div className="chart-frame"><ResponsiveContainer width="100%" height="100%">{children}</ResponsiveContainer></div>}
function Empty(){return <div className="chart-empty">Log more trades to populate this chart.</div>}
