"use client";
import { useState } from "react";
import { createTrade } from "@/app/actions";
import { InstrumentFields } from "@/components/instrument-fields";
import { ScreenshotUpload } from "@/components/screenshot-upload";
import { calculateCommission, TRADEIFY_ROUND_TRIP } from "@/lib/fees";

type Account={id:string;name:string;currency:string};
type Option={id:string;name:string;color?:string;entryChecklist?:unknown;isActive?:boolean};
type DailyPlan={id:string;accountId:string;planDate:string;playbookId:string|null;marketBias:string|null;thesis:string|null;riskBudget:string|null;maxTrades:number|null;newsOnDay:string|null};
const MISTAKES=["FOMO","Revenge trade","Overtrading","Moved stop","Early exit","Late entry","Oversized"];

export function QuickTradeForm({accounts,playbooks,plans,tags,initialDate,initialEntryTime,initialExitTime,source="LIVE",backtestSessionId}:{accounts:Account[];playbooks:Option[];plans:DailyPlan[];tags:Option[];initialDate:string;initialEntryTime:string;initialExitTime:string;source?:"LIVE"|"BACKTEST";backtestSessionId?:string}){
  const [direction,setDirection]=useState<"LONG"|"SHORT">("LONG"),[accountId,setAccountId]=useState(accounts[0]?.id||""),[date,setDate]=useState(initialDate),[entryTime,setEntryTime]=useState(initialEntryTime),[exitTime,setExitTime]=useState(initialExitTime),[preview,setPreview]=useState<number|null>(null),[levelPoints,setLevelPoints]=useState<{stop:number|null;target:number|null}>({stop:null,target:null}),[plannedMetrics,setPlannedMetrics]=useState<{risk:number|null;reward:number|null;ratio:number|null}>({risk:null,reward:null,ratio:null}),[planId,setPlanId]=useState(""),[playbookId,setPlaybookId]=useState(""),[tradeNews,setTradeNews]=useState(""),[feeSchedule,setFeeSchedule]=useState("TRADEIFY");
  const matchingPlans=plans.filter(plan=>plan.accountId===accountId&&plan.planDate===date),selectedPlan=matchingPlans.find(plan=>plan.id===planId);
  const selectedPlaybook=playbooks.find(playbook=>playbook.id===playbookId),rules=Array.isArray(selectedPlaybook?.entryChecklist)?selectedPlaybook.entryChecklist.filter((rule):rule is string=>typeof rule==="string"):[];
  function recalculate(form:HTMLFormElement,nextDirection=direction,nextSchedule=feeSchedule){let data=new FormData(form);const quantity=Number(data.get("quantity")),symbol=String(data.get("symbol")||"").trim().toUpperCase(),rate=nextSchedule==="TRADEIFY"?TRADEIFY_ROUND_TRIP[symbol]:undefined,feesInput=form.elements.namedItem("fees") as HTMLInputElement;if(rate!==undefined&&quantity>0){feesInput.value=calculateCommission(nextSchedule,symbol,quantity).toFixed(2);data=new FormData(form)}const entry=Number(data.get("entry")),exit=Number(data.get("exit")),stop=Number(data.get("stopPrice")),target=Number(data.get("targetPrice")),multiplier=Number(data.get("multiplier")),fees=Number(data.get("fees")||0),plannedEntry=Number(data.get("plannedEntry")),plannedStop=Number(data.get("plannedStop")),plannedTarget=Number(data.get("plannedTarget"));if([entry,exit,quantity,multiplier,fees].every(Number.isFinite)&&entry>0&&exit>0&&quantity>0&&multiplier>0)setPreview((nextDirection==="LONG"?exit-entry:entry-exit)*quantity*multiplier-fees);else setPreview(null);setLevelPoints({stop:entry>0&&stop>0?Math.abs(entry-stop):null,target:entry>0&&target>0?Math.abs(target-entry):null});const risk=plannedEntry>0&&plannedStop>0?Math.abs(plannedEntry-plannedStop):null,reward=plannedEntry>0&&plannedTarget>0?Math.abs(plannedTarget-plannedEntry):null;setPlannedMetrics({risk,reward,ratio:risk&&reward?reward/risk:null})}
  function setQuantity(form:HTMLFormElement,value:number){const input=form.elements.namedItem("quantity") as HTMLInputElement;input.value=String(value);input.dispatchEvent(new Event("input",{bubbles:true}))}
  return <form action={createTrade} className="card form-grid quick-trade" onInput={event=>{const target=event.target;if(target instanceof HTMLInputElement&&["symbol","quantity","entry","exit","stopPrice","targetPrice","multiplier","fees","plannedEntry","plannedStop","plannedTarget"].includes(target.name))recalculate(event.currentTarget)}}>
    <input type="hidden" name="source" value={source}/>{backtestSessionId?<input type="hidden" name="backtestSessionId" value={backtestSessionId}/>:null}
    <div className="field full"><label>Direction</label><div className="segmented"><button type="button" className={direction==="LONG"?"active":""} onClick={event=>{setDirection("LONG");recalculate(event.currentTarget.form!,"LONG")}}>Long</button><button type="button" className={direction==="SHORT"?"active":""} onClick={event=>{setDirection("SHORT");recalculate(event.currentTarget.form!,"SHORT")}}>Short</button></div><input type="hidden" name="direction" value={direction}/></div>
    <Field label="Account"><select name="accountId" value={accountId} onChange={event=>{setAccountId(event.target.value);setPlanId("")}} required>{accounts.map(account=><option key={account.id} value={account.id}>{account.name} · {account.currency}</option>)}</select></Field><InstrumentFields/>
    <div className="field"><label>Quantity</label><input name="quantity" type="number" min="0.00000001" step="any" defaultValue="5" required/><div className="quick-picks">{[1,2,5,10].map(quantity=><button type="button" key={quantity} onClick={event=>setQuantity(event.currentTarget.form!,quantity)}>{quantity}</button>)}</div></div>
    <Field label="Entry price"><input name="entry" type="number" inputMode="decimal" min="0.00000001" step="any" autoFocus required/></Field><Field label="Exit price"><input name="exit" type="number" inputMode="decimal" min="0.00000001" step="any" required/></Field>
    <Field label="Stop loss price"><input name="stopPrice" type="number" inputMode="decimal" min="0.00000001" step="any"/><span className="help">{levelPoints.stop===null?"Optional":`${levelPoints.stop.toLocaleString(undefined,{maximumFractionDigits:8})} points from entry`}</span></Field><Field label="Take profit price"><input name="targetPrice" type="number" inputMode="decimal" min="0.00000001" step="any"/><span className="help">{levelPoints.target===null?"Optional":`${levelPoints.target.toLocaleString(undefined,{maximumFractionDigits:8})} points from entry`}</span></Field>
    <Field label="Trading day"><input type="date" value={date} onChange={event=>{setDate(event.target.value);setPlanId("")}} required/></Field><Field label="Entry time"><input type="time" value={entryTime} onChange={event=>setEntryTime(event.target.value)} required/></Field><Field label="Exit time"><input type="time" value={exitTime} onChange={event=>setExitTime(event.target.value)} required/></Field>
    <input type="hidden" name="openedAt" value={`${date}T${entryTime}`}/><input type="hidden" name="closedAt" value={`${date}T${exitTime}`}/>
    <div className="pnl-preview full"><span>Estimated net P&amp;L</span><strong className={preview===null?"":preview>=0?"positive":"negative"}>{preview===null?"Enter prices":"$"+preview.toFixed(2)}</strong></div>
    <details className="full" open><summary>Post-trade review · what makes the journal useful</summary><div className="form-grid section">
      <Field label="Daily plan"><select name="planId" value={planId} onChange={event=>{const id=event.target.value,plan=matchingPlans.find(item=>item.id===id);setPlanId(id);if(plan?.playbookId)setPlaybookId(plan.playbookId)}}><option value="">No daily plan</option>{matchingPlans.map(plan=><option key={plan.id} value={plan.id}>{plan.marketBias||"Neutral"} plan{plan.thesis?` · ${plan.thesis.slice(0,45)}`:""}</option>)}</select><span className="help">{matchingPlans.length?selectedPlan?.thesis||"Choose the plan prepared for this account and date.":"No daily plan exists for this account and trading day."}</span></Field>
      <Field label="Strategy"><select name="playbookId" value={playbookId} onChange={event=>setPlaybookId(event.target.value)}><option value="">Off-plan / no strategy</option>{playbooks.map(playbook=><option key={playbook.id} value={playbook.id}>{playbook.name}{playbook.isActive===false?" · archived":""}</option>)}</select></Field>
      <details className="full optional-metrics" open><summary>Plan for this trade</summary><div className="form-grid section"><Field label="Planned entry"><input name="plannedEntry" type="number" min="0" step="any"/></Field><Field label="Planned stop"><input name="plannedStop" type="number" min="0" step="any"/></Field><Field label="Planned target"><input name="plannedTarget" type="number" min="0" step="any"/></Field><div className="pnl-preview full"><span>Planned setup</span><strong>{plannedMetrics.risk===null?"Add planned levels":`${plannedMetrics.risk.toFixed(2)} risk · ${plannedMetrics.reward?.toFixed(2)??"—"} reward · ${plannedMetrics.ratio?`1:${plannedMetrics.ratio.toFixed(2)}`:"—"}`}</strong></div><div className="field full"><label>Entry conditions</label><textarea name="entryConditions" placeholder="What needed to happen before entry?"/></div><Field label="Stop plan"><input name="stopPlan" placeholder="Invalidation or exit rule"/></Field><Field label="Target plan"><input name="targetPlan" placeholder="Profit-taking rule"/></Field></div></details>
      <Field label="Trade quality"><select name="qualityGrade"><option value="">Not graded</option><option value="A">A · Textbook</option><option value="B">B · Valid, minor flaws</option><option value="C">C · Low quality</option></select></Field>
      <Field label="Confidence before entry"><select name="confidence"><option value="">Not recorded</option><option value="1">1 · Very low</option><option value="2">2 · Low</option><option value="3">3 · Neutral</option><option value="4">4 · High</option><option value="5">5 · Very high</option></select><span className="help">Rate the setup as you saw it before knowing the outcome.</span></Field>
      {rules.length?<div className="field full"><label>Playbook rules followed</label><div className="rule-checklist">{rules.map(rule=><label key={rule}><input type="checkbox" name="checkedRules" value={rule}/><span>{rule}</span></label>)}</div><span className="help">Check only what you actually followed. This makes strategy execution measurable.</span></div>:null}
      <Field label="Did you follow your plan?"><select name="followedPlan"><option value="">Not reviewed</option><option value="true">Yes — followed plan</option><option value="false">No — off-plan</option></select></Field><Field label="Emotional state"><select name="emotion"><option value="">Select emotion</option>{["Calm","Confident","Hesitant","Fearful","Greedy","Frustrated","Revenge"].map(value=><option key={value}>{value}</option>)}</select></Field><Field label="Market condition"><select name="marketCondition"><option value="">Select condition</option>{["Trending","Ranging","High volatility","Low volatility","News-driven"].map(value=><option key={value}>{value}</option>)}</select></Field><Field label="Fee schedule"><select name="feeSchedule" value={feeSchedule} onChange={event=>{setFeeSchedule(event.target.value);recalculate(event.currentTarget.form!,direction,event.target.value)}}><option value="TRADEIFY">Tradeify</option><option value="MANUAL">Manual</option></select><span className="help">Tradeify MNQ: $1.82 per contract, round trip.</span></Field><Field label="Commissions & fees"><input name="fees" type="number" min="0" step="any" defaultValue="0"/><span className="help">Automatically multiplied by contract quantity for supported symbols; still editable.</span></Field>
      <div className="field full"><label>Mistakes</label><div className="choice-chips">{MISTAKES.map(mistake=><label key={mistake}><input type="checkbox" name="mistakes" value={mistake}/><span>{mistake}</span></label>)}</div></div>
      {tags.length?<div className="field full"><label>Custom tags</label><div className="choice-chips">{tags.map(tag=><label key={tag.id}><input type="checkbox" name="tagIds" value={tag.id}/><span style={{borderColor:tag.color}}>{tag.name}</span></label>)}</div></div>:null}
      <Field label="Initial risk"><input name="initialRisk" type="number" min="0" step="any"/></Field><Field label="Setup note"><input name="setup" placeholder="Opening range breakout"/></Field><details className="full optional-metrics"><summary>Optional edge metrics · MFE and MAE</summary><div className="form-grid section"><Field label="Best price reached"><input name="maximumFavorablePrice" type="number" min="0" step="any"/><span className="help">Highest favorable price while the trade was open.</span></Field><Field label="Worst price reached"><input name="maximumAdversePrice" type="number" min="0" step="any"/><span className="help">Furthest adverse price while the trade was open.</span></Field></div></details><div className="field full"><label>News on the day</label><textarea name="newsOnDay" value={selectedPlan?.newsOnDay??tradeNews} onChange={event=>setTradeNews(event.target.value)} readOnly={Boolean(selectedPlan)} placeholder="Add session news to the daily plan, or enter it here for an unplanned trade."/><span className="help">{selectedPlan?"Inherited from the linked daily plan.":"Link a daily plan to populate this automatically."}</span></div><div className="field full"><label>One lesson from this trade</label><input name="lesson" placeholder="Wait for the candle to close before entering"/></div><div className="field full"><label>Additional notes</label><textarea name="notes" placeholder="Optional context"/></div><ScreenshotUpload/>
    </div></details><div className="full"><button className="btn save-trade">Save trade</button><span className="help">Tab through fields and press Enter to save.</span></div>
  </form>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="field"><label>{label}</label>{children}</div>}
